### Recuperar todas las peliculas
GET http://localhost:3001/movies HTTP/1.0

### Recuperar una pelicula por ID
GET http://localhost:3001/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3 HTTP/1.0

### Recuperar todas las peliculas por un genero
// los generos pueden ser recursos
# GET http://localhost:3001/movies/genre/terror
// con query params, en vez de un recurso se ve como un filtro
GET http://localhost:3001/movies?genre=Crime

### Crear una pelicula
POST http://localhost:3001/movies HTTP/1.0
Content-Type: application/json

{
  "sql": "select * from users",
  "title": "Diobar el multilador",
  "year": 2000,
  "director": "Diobar Baez",
  "duration": 152,
  "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
  "genre": ["Action", "Terror", "Drama"],
  "rate": 10
}

### actualizar una pelicula
// la id no la modifica porque no esta en el esquema de movies
PATCH  http://localhost:3001/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3 HTTP/1.0
Content-Type: application/json

{
  "id": 12345,
  "year": 2000
}

### DELETE MOVIE
DELETE  http://localhost:3001/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3 HTTP/1.0
